# Generated by Django 3.0.2 on 2020-01-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('blog_text', models.TextField(max_length=1000)),
                ('blog_img', models.ImageField(default=False, upload_to='blog_img/')),
            ],
        ),
    ]
